/*CREATE TABLE ACCOUNT(
    ID NUMBER PRIMARY KEY,
    USER_NAME VARCHAR2(20) NOT NULL,
    USER_CITY VARCHAR2(100) NOT NULL,
    USER_STATE VARCHAR2(100) NOT NULL,
    USER_COUNTRY VARCHAR2(100) NOT NULL,
    USER_PIN_CODE NUMBER(6) NOT NULL,
    USER_BALANCE NUMBER DEFAULT 0,
    CONSTRAINT CHKID CHECK (ID >= 111111 AND ID<=999999),
    CONSTRAINT CHKPIN CHECK (USER_PIN_CODE >= 111111 AND USER_PIN_CODE<=999999)
);

DROP TABLE ACCOUNT;

CREATE TABLE HISTORY(
    ID NUMBER,
    OLD_BALANCE NUMBER,
    NEW_BALANCE NUMBER,
    AMOUNT_DORW NUMBER,
    CURR_DATE VARCHAR2(20),
    STATUS VARCHAR2(20),
    CONSTRAINT CHKIDH CHECK (ID >= 111111 AND ID<=999999),
    CONSTRAINT FK_ID FOREIGN KEY (ID)
    REFERENCES ACCOUNT(ID)  
);

DROP TABLE HISTORY;

SELECT
    *
FROM
    ACCOUNT;

SELECT
    *
FROM
    HISTORY;

*/

CREATE TABLE DELETEACCOUNT(
    ID NUMBER,
    CURR_DATE VARCHAR2(20),
    STATUS VARCHAR2(120),
    CONSTRAINT CHKIDD CHECK (ID >= 111111 AND ID<=999999)
);

DECLARE
    ACCOUNT_TYPE ACCOUNT%ROWTYPE;
BEGIN
    ACCOUNT_TYPE.ID:=&ID;
    ACCOUNT_TYPE.USER_NAME:=&USER_NAME;
    ACCOUNT_TYPE.USER_CITY:=&USER_CITY;
    ACCOUNT_TYPE.USER_STATE:=&USER_STATE;
    ACCOUNT_TYPE.USER_COUNTRY:=&USER_COUNTRY;
    ACCOUNT_TYPE.USER_PIN_CODE:=&USER_PIN_CODE;
    INSERT INTO ACCOUNT(
        ID,
        USER_NAME,
        USER_CITY,
        USER_STATE,
        USER_COUNTRY,
        USER_PIN_CODE
    ) VALUES(
        ACCOUNT_TYPE.ID,
        ACCOUNT_TYPE.USER_NAME,
        ACCOUNT_TYPE.USER_CITY,
        ACCOUNT_TYPE.USER_STATE,
        ACCOUNT_TYPE.USER_COUNTRY,
        ACCOUNT_TYPE.USER_PIN_CODE
    );
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE('Account Id is not unique');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error!');
END;
SELECT
    *
FROM
    ACCOUNT;
