DECLARE
    ACCOUNTID    ACCOUNT.ID%TYPE;
    ACCOUNT_TYPE ACCOUNT%ROWTYPE;
    CURR_DATE    VARCHAR2(20);
BEGIN
    ACCOUNTID:=&ACCOUNTID;
    SELECT
        ID,
        USER_NAME,
        USER_BALANCE INTO ACCOUNT_TYPE.ID,
        ACCOUNT_TYPE.USER_NAME,
        ACCOUNT_TYPE.USER_BALANCE
    FROM
        ACCOUNT
    WHERE
        ID=ACCOUNTID;
    IF ACCOUNT_TYPE.USER_BALANCE !=0 THEN
        DBMS_OUTPUT.PUT_LINE('USER BALANCE  IS NOT ZERO PLEASE WITHDRAW YOUR BALANCE FIRST');
    ELSE
        SELECT
            TO_CHAR (SYSDATE,
            'DD-MM-YYYY HH24:MI:SS') INTO CURR_DATE
        FROM
            DUAL;
        INSERT INTO DELETEACCOUNT(
            ID,
            CURR_DATE,
            STATUS
        ) VALUES(
            ACCOUNT_TYPE.ID,
            CURR_DATE,
            'DELETED'
        );
        DELETE FROM ACCOUNT
        WHERE
            ID=ACCOUNTID;
        COMMIT;
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO DATA FOUND');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error!');
END;