DECLARE
    BALANCE     ACCOUNT.USER_BALANCE%TYPE;
    ACCOUNTID   ACCOUNT.ID%TYPE;
    AMOUNT      NUMBER;
    AMOUNT_DORW NUMBER;
    CURR_DATE   VARCHAR2(20);
BEGIN
    ACCOUNTID:=&ACCOUNTID;
    AMOUNT:=&AMOUNT;
    AMOUNT_DORW:=AMOUNT;
    SELECT
        USER_BALANCE INTO BALANCE
    FROM
        ACCOUNT
    WHERE
        ID=ACCOUNTID;
    AMOUNT:=AMOUNT+BALANCE;
    SELECT
        TO_CHAR (SYSDATE,
        'DD-MM-YYYY HH24:MI:SS') INTO CURR_DATE
    FROM
        DUAL;
    INSERT INTO HISTORY VALUES(
        ACCOUNTID,
        BALANCE,
        AMOUNT,
        AMOUNT_DORW,
        CURR_DATE,
        'DEPOSIT'
    );
    UPDATE ACCOUNT
    SET
        USER_BALANCE =AMOUNT
    WHERE
        ID=ACCOUNTID;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE( 'DEPOSIT successfull');
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO DATA FOUND');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error!');
END;